name: Build and Deploy PC & WebGL

on:
  push:
    branches: [ main ]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - WebGL
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }} # Use the masked serial
        with:
          unityVersion: 6000.0.32f1
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: MyGame-${{ matrix.targetPlatform }}
          buildDirectory: build/${{ matrix.targetPlatform }}

      - name: Deploy to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          ITCH_GAME: 3knot3
          ITCH_USER: sarwar2arnob
          PACKAGE: ./build/${{ matrix.targetPlatform }}
          CHANNEL: ${{ matrix.targetPlatform }}