name: Build and Deploy PC & WebGL

on:
  push:
    branches: [ main ]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true # If your project uses Git LFS

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }} # Set this secret if you have a Pro/Enterprise license
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}     # Set this secret with your Unity account email
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }} # Set this secret with your Unity account password
        with:
          unityVersion: 6000.0.32f1
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: MyGame-${{ matrix.targetPlatform }}
          buildDirectory: build/${{ matrix.targetPlatform }}

      - name: Deploy to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }} # Use the secret you already set
          ITCH_GAME: 3knot3
          ITCH_USER: sarwar2arnob
          PACKAGE: ./build/${{ matrix.targetPlatform }}
          CHANNEL: ${{ matrix.targetPlatform }} # Uses the target platform as the channel