name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    name: Analyze Unity Project with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_studio71
            -Dsonar.organization=learnathon-by-geeky-solutions
            -Dsonar.sources=Assets/Scripts
            -Dsonar.exclusions=**/*.meta,Library/**,Temp/**,obj/**,Build/**,Packages/**,Assets/Plugins/**
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
